### ISSUE TITLE
OrganizationalUnitName

### ISSUE THREAD

**Issue by ri-we** [Azure-Samples/azure-files-samples#17]
The parameter OrganizationalUnitName looks to have an issue with spaces in the OU name.

**Comment by YunZhou-MS** [comment]
Hi ri-we,

Could you help clarify what the issue you saw? What is the command you ran? What is the error message?

Thanks,
Yun

**Comment by NebV** [comment]
I'm assuming I had the same issue.  Under the Join-AzStorageAccountForAuth section, I used `OrganizationalUnitName "Azure File Shares"` and this did not work and ended up putting the account in the same directory as my user account.

**Comment by YunZhou-MS** [comment]
Hi NebV,

Thank you for reporting your issue!
As far as I know the script doesn't have any limitation on using OrganizationalUnitName with spaces in the name for Join-AzStorageAccountForAuth. The issue you reported seems to be different. To better understand your issue, could you help with a few questions?
1. Does OU "Azure File Shares" exist in the directory where you intended to join your storage account?
2. Does OU "Azure File Shares" exist in the directory where your user account exists?
3. What is the command line you used to call Join-AzStorageAccountForAuth?

Thanks,
Yun

**Comment by NebV** [comment]
1. Yes
2. No - this could be the issue
3. ```
Join-AzStorageAccountForAuth `
        -ResourceGroupName $ResourceGroupName `
        -Name $StorageAccountName `
        -DomainAccountType "ServiceLogonAccount" `
        -OrganizationalUnitName "Azure File Shares"
```

**Comment by YunZhou-MS** [comment]
Hi @NebV,

The cmdlet Join-AzStorageAccountForAuth supports an input parameter -Domain to specify the directory where you want to join the storage account. Previously, the default value for the parameter -Domain is the one where the logged on user account is located, and that is why you saw your account was created in the same directory as your user account. With the [latest release](https://github.com/Azure-Samples/azure-files-samples/releases/latest) of powershell module, we made a fix so that default domain will be the one where your computer account exists if the parameter -DomainAccountType is "ComputerAccount" and the one where your user account exists if the parameter -DomainAccountType is "ServiceLogonAccount". In any case, you can always overwrite the default behavior by explicitly providing the parameter -Domain. Hope this helps address your needs.

Best regards,
Yun
